version: '3'

services:

  broker:
    image: confluentinc/cp-server:7.9.1
    hostname: broker
    container_name: broker
    ports:
      - "9092:9092"
      - "9101:9101"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://broker:29092,PLAINTEXT_HOST://localhost:9092'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_CONFLUENT_LICENSE_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CONFLUENT_BALANCER_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"
      KAFKA_JMX_PORT: 9101
      KAFKA_JMX_HOSTNAME: localhost
      KAFKA_CONFLUENT_SCHEMA_REGISTRY_URL: http://schema-registry:8081
      KAFKA_METRIC_REPORTERS: io.confluent.metrics.reporter.ConfluentMetricsReporter
      CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS: broker:29092
      CONFLUENT_METRICS_REPORTER_TOPIC_REPLICAS: 1
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@broker:29093'
      KAFKA_LISTENERS: 'PLAINTEXT://broker:29092,CONTROLLER://broker:29093,PLAINTEXT_HOST://0.0.0.0:9092'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_LOG_DIRS: '/tmp/kraft-combined-logs'
      CONFLUENT_METRICS_ENABLE: 'true'
      CONFLUENT_SUPPORT_CUSTOMER_ID: 'anonymous'
      # Replace CLUSTER_ID with a unique base64 UUID using "bin/kafka-storage.sh random-uuid"
      # See https://docs.confluent.io/kafka/operations-tools/kafka-tools.html#kafka-storage-sh
      CLUSTER_ID: 'MkU3OEVBNTcwNTJENDM2Qk'

  # This "container" is a workaround to pre-create topics for the Kafka Music application
  # until we have a more elegant way to do that.
  kafka-create-topics:
    image: confluentinc/cp-kafka:7.9.1
    depends_on:
      - broker
    hostname: kafka-create-topics
    # We defined a dependency on "kafka", but `depends_on` will NOT wait for the
    # dependencies to be "ready" before starting the "kafka-create-topics"
    # container;  it waits only until the dependencies have started.  Hence we
    # must control startup order more explicitly.
    # See https://docs.docker.com/compose/startup-order/
    command: "bash -c 'echo Waiting for Kafka to be ready... && \
                       cub kafka-ready -b broker:29092 1 20 && \
                       kafka-topics --create --topic stream-stream-order-topic --if-not-exists --bootstrap-server broker:29092 --partitions 4 --replication-factor 1 && \
                       kafka-topics --create --topic stream-stream-address-topic --if-not-exists --bootstrap-server broker:29092 --partitions 4 --replication-factor 1 && \
                       kafka-topics --create --topic stream-stream-output-topic --if-not-exists --bootstrap-server broker:29092 --partitions 4 --replication-factor 1 && \
                       kafka-topics --create --topic stream-table-order-topic --if-not-exists --bootstrap-server broker:29092 --partitions 4 --replication-factor 1 && \
                       kafka-topics --create --topic stream-table-address-topic --if-not-exists --bootstrap-server broker:29092 --partitions 4 --replication-factor 1 && \
                       kafka-topics --create --topic stream-table-output-topic --if-not-exists --bootstrap-server broker:29092 --partitions 4 --replication-factor 1 && \
                       kafka-topics --create --topic table-table-order-topic --if-not-exists --bootstrap-server broker:29092 --partitions 4 --replication-factor 1 && \
                       kafka-topics --create --topic table-table-address-topic --if-not-exists --bootstrap-server broker:29092 --partitions 4 --replication-factor 1 && \
                       kafka-topics --create --topic table-table-output-topic --if-not-exists --bootstrap-server broker:29092 --partitions 4 --replication-factor 1 && \
                       kafka-topics --create --topic stream-gtable-order-topic --if-not-exists --bootstrap-server broker:29092 --partitions 4 --replication-factor 1 && \
                       kafka-topics --create --topic stream-gtable-address-topic --if-not-exists --bootstrap-server broker:29092 --partitions 4 --replication-factor 1 && \
                       kafka-topics --create --topic stream-gtable-output-topic --if-not-exists --bootstrap-server broker:29092 --partitions 4 --replication-factor 1 && \
                       sleep infinity'"
    environment:
      # The following settings are listed here only to satisfy the image's requirements.
      # We override the image's `command` anyways, hence this container will not start a broker.
      KAFKA_BROKER_ID: ignored
      KAFKA_ZOOKEEPER_CONNECT: ignored
    extra_hosts:
      - "moby:127.0.0.1"

  schema-registry:
    image: confluentinc/cp-schema-registry:7.9.1
    hostname: schema-registry
    container_name: schema-registry
    depends_on:
      - broker
    ports:
      - "8081:8081"
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: 'broker:29092'
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081

  control-center:
    image: confluentinc/cp-enterprise-control-center:7.9.1
    hostname: control-center
    container_name: control-center
    depends_on:
      - broker
      - schema-registry
    ports:
      - "9021:9021"
    environment:
      CONTROL_CENTER_BOOTSTRAP_SERVERS: 'broker:29092'
      CONTROL_CENTER_SCHEMA_REGISTRY_URL: "http://schema-registry:8081"
      CONTROL_CENTER_REPLICATION_FACTOR: 1
      CONTROL_CENTER_INTERNAL_TOPICS_PARTITIONS: 1
      CONTROL_CENTER_MONITORING_INTERCEPTOR_TOPIC_PARTITIONS: 1
      CONFLUENT_METRICS_TOPIC_REPLICATION: 1
      PORT: 9021

  stream-stream:
    build: .
    container_name: stream-stream
    command: ["studio.goodlabs.StreamStreamJoinApp"]
    environment:
      KAFKA_BOOTSTRAP_SERVERS: 'broker:29092'

  stream-table:
    build: .
    container_name: stream-table
    command: ["studio.goodlabs.StreamTableJoinApp"]
    environment:
      KAFKA_BOOTSTRAP_SERVERS: 'broker:29092'

  table-table:
    build: .
    container_name: table-table
    command: ["studio.goodlabs.TableTableJoinApp"]
    environment:
      KAFKA_BOOTSTRAP_SERVERS: 'broker:29092'

  stream-global:
    build: .
    container_name: stream-global
    command: ["studio.goodlabs.StreamGTableJoinApp"]
    environment:
      KAFKA_BOOTSTRAP_SERVERS: 'broker:29092'
